/*
Deployment script for tttt

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tttt"
:setvar DefaultFilePrefix "tttt"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
PRINT N'Creating SqlTable [dbo].[ExampleTable]...';


GO
CREATE TABLE [dbo].[ExampleTable] (
    [Id]     INT             NOT NULL,
    [Amount] DECIMAL (13, 3) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating SqlInlineTableValuedFunction [dbo].[CalculateDiscount]...';


GO
/*--
DROP FUNCTION IF EXISTS dbo.CalculateDiscount;
GO
--*/
CREATE FUNCTION [dbo].[CalculateDiscount]
(
	@Value NUMERIC(13,2)
)
RETURNS TABLE
AS
RETURN
  SELECT CASE WHEN @Value >= 50 THEN @Value * 0.10 ELSE 0 END discount;
GO
PRINT N'Creating SqlProcedure [dbo].[ExampleProcedure]...';


GO
CREATE PROCEDURE [dbo].[ExampleProcedure]
AS
BEGIN
  SELECT AVG(Amount)
    FROM dbo.ExampleTable
END;
GO
PRINT N'Update complete.';


GO
