name: SQL container in pipeline
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # service/sidecar container for azure-sql-2022
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: 1
          SA_PASSWORD: P@ssw0rd
        ports:
          - 1433:1433

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'wait for sql to be ready'
        run: |
          set +o pipefail +e
          for i in {1..60};
          do
              sqlcmd -S localhost -U sa -P P@ssw0rd -d master -Q "select getdate()"
              if [ $? -eq 0 ]
              then
                  echo "sql server ready"
                  break
              else
                  echo "not ready yet..."
                  sleep 1
              fi
          done
          set -o pipefail -e

      - name: create an empty DB
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d master -Q "create database test123;"
          sleep 10

      # deploy the sql project
      - uses: azure/sql-action@v1.3
        with:
          connection-string: "Server=localhost;Initial Catalog=test123;User ID=sa;Password=P@ssw0rd;"  # the local connection string
          project-file: './Code/Code.sqlproj' # the SQLproj file

      - uses: azure/sql-action@v1.3
        with:
          connection-string: "Server=localhost;Initial Catalog=test123;User ID=sa;Password=P@ssw0rd;"  # the local connection string
          project-file: './Tests/Tests.sqlproj' # the SQLproj file
          
      - name: run a query
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d test123 -Q "exec testFinancialApp.[test that Report gets sales data with converted currency]"

      - name: run a query2
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d test123 -Q "sp_helptext '[test that Report gets sales data with converted currency]'"

      - name: run a query3
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d test123 -Q "sp_helptext '[tSQLt].[Run]';"          